services:
  telegram-bot:
    image: vovsn/test-bot
    container_name: test-bot
    env_file:
      - .env
    volumes:
      - test-bot-data:/app
    ports:
      - "8081:8081"
    restart: always

volumes:
  test-bot-data: